### ISSUE TITLE
Docker executors volume mount error

### ISSUE THREAD

**Issue by jhuang732** [dagu-org/dagu#1044]
I'm following the [Volume Mount example from documentation](https://docs.dagu.cloud/features/executors/docker#volume-mounts) and it's showing the error below when trying to bind with `${PWD}`. The same error occurs with something like this `- ./output:/output:rw `

```
failed to execute step "foo": Error response from daemon: create ${PWD}/data: "${PWD}/data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
```

And when using the absolute path `/var/lib/dagu/dags/data`, it doesn't recognize any files that I want to execute inside the container.

**Comment by yohamta0** [comment]
Hi @jhuang732, this issue should be fixed in the latest version. Thank you so much for helping improve Dagu! Let us know if you run into anything else.

**Comment by jhuang732** [comment]
@yottahmd thank you! The file expansion seems to work now but I'm still unable to get a file to execute in a docker container task. Is it right to assume that the "host" file should be place in `/var/lib/dagu/dags/data`?

**Comment by yohamta0** [comment]
Hi @jhuang732, I might be missing something here. Could you clarify what the “host” file refers to in this context? Also, which Docker image are you running with the Docker executor?

If you're trying to bind a path to the directory containing the DAG YAML files, that would be `/var/lib/dagu/dags` inside the Dagu image's container.

**Comment by jhuang732** [comment]
@yottahmd here's the current setup. I'm trying to execute `post.py` in the `hello.yaml` DAG

`/dagu_config/dags/hello.yaml`
```
steps:
  - name: foo
    executor:
      type: docker
      config:
        image: python:3.13-alpine
        container:
          workingDir: /data
        autoRemove: true
        host:
          binds:
            - ${PWD}/data:/data
    command: python post.py
```

`/dagu_config/dags/data/post.py`
```
if __name__ == "__main__":
    print("PROCESSED")
```

`/docker-compose.yaml`
```
services:
  dagu:
    image: "ghcr.io/dagu-org/dagu:1.17.3"
    container_name: dagu
    hostname: dagu
    ports:
      - "8080:8080"
    volumes:
      - ./dagu_config:/var/lib/dagu
      - /var/run/docker.sock:/var/run/docker.sock
    user: "0:0"
    entrypoint: []
```

**Comment by yohamta0** [comment]
@jhuang732 Sorry for the late response. When using Docker-in-Docker (DinD), you need to mount volumes using the **host machine's path**, not the path inside the DinD container.

This happens because when you mount the Docker socket, your Docker commands are actually sent to the host's Docker daemon, not a daemon inside the container. So volume paths are resolved from the host's perspective.

Here's how to fix it:

```diff
services:
  dagu:
    image: "ghcr.io/dagu-org/dagu:1.17.3"
    container_name: dagu
    hostname: dagu
    ports:
      - "8080:8080"
    volumes:
-      - ./dagu_config:/var/lib/dagu
+      - /Users/yottahmd/dev/dagu_config/dags/data:/var/lib/dagu
      - /var/run/docker.sock:/var/run/docker.sock
    user: "0:0"
    entrypoint: []
```

Let me know if there's any further issues!
