### ISSUE TITLE
Timeout issues when running locally

### ISSUE THREAD

**Issue by jrisch** [dagu-org/dagu#1160]
I'm trying to develop some dags right now, and I run dagu locally. It worked fine in the beginning, but now I get timeout issues, even though I'm the only one using the server, and nothing else is running:

```text
time=2025-08-04T10:56:04.524+02:00 level=DEBUG source=/home/runner/work/dagu/dagu/internal/persistence/filequeue/reader.go:153 msg="Backup polling reload"
time=2025-08-04T10:56:04.643+02:00 level=INFO source=/home/runner/work/dagu/dagu/internal/persistence/filequeue/reader.go:324 msg="Channel full, delaying retry" name=subdomain-enumeration retryAfter=2025-08-04T10:56:06+02:00
time=2025-08-04T10:56:04.676+02:00 level=ERROR source=/home/runner/work/dagu/dagu/internal/scheduler/scheduler.go:378 msg="Timeout waiting for run to start" data=subdomain-enumeration:a2
time=2025-08-04T10:56:04.676+02:00 level=INFO source=/home/runner/work/dagu/dagu/internal/scheduler/scheduler.go:263 msg="Received item from queue" data=subdomain-enumeration:a2
```

The dag:

```yaml
name: subdomain-enumeration
description: Enumerates subdomains for a given domain using subfinder
queue: batch
#maxActiveRuns: 3

params:
  - DOMAIN: domain-name.io
  - OUTPUT_DIR: /tmp/scan-results
  - OUTPUT_FILE: subdomains.txt

steps:
  - name: subdomain-enumeration
    executor:
      type: docker
      config:
        image: projectdiscovery/subfinder:latest
        host:
          binds:
            - "$OUTPUT_DIR:/output"
        container:
          env:
            - DOMAIN=$DOMAIN
            - OUTPUT_FILE=$OUTPUT_FILE
    command: -d $DOMAIN -o /output/$OUTPUT_FILE
    depends:
      - setup-output-directory
    output: DOMAIN_LIST
```

The server `config-dev.yaml` file:

```yaml
---
cors:
  enabled: false
  #allowedOrigins:
  #  - https://app.example.com
queues:
  enabled: true
  config:
    - name: "critical"
      maxActiveRuns: 5      # 5 critical jobs concurrently
    - name: "batch"
      maxActiveRuns: 1      # One batch job at a time
    - name: "reporting"
      maxActiveRuns: 3      # 3 reports concurrently
host: "127.0.0.1"
port: 8080
debug: true

paths:
  dagsDir: "./dags"               # DAG definitions
  workDir: "./workspace"          # Default working directory
  logDir: "./logs"                # Log files
  dataDir: "./data"               # Application data
  suspendFlagsDir: "./suspend"    # Suspend flags
  adminLogsDir: "./logs/admin"    # Admin logs
  baseConfig: "./base.yaml"       # Base configuration
```

I start dagu with this command: `dagu start-all -c config-dev.yaml`

**Comment by jrisch** [comment]
Let me add: I've tried to remove the data, logs and suspend dirs, and the error persist.

**Comment by yohamta0** [comment]
I'll fix the scheduler issue soon. Thank you for sharing details.

**Comment by yohamta0** [comment]
This issue should be resolved in version 1.19.0. Please give it a try. Thank you for helping improve Dagu!

**Comment by jrisch** [comment]
The new version still have the same issue:

```
time=2025-08-07T10:25:48.880+02:00 level=ERROR source=/home/runner/work/dagu/dagu/internal/scheduler/scheduler.go:395 msg="Timeout waiting for run to start" data=subdomain-enumeration:a1
time=2025-08-07T10:25:48.880+02:00 level=INFO source=/home/runner/work/dagu/dagu/internal/scheduler/scheduler.go:284 msg="Received item from queue" data=subdomain-enumeration:a1
time=2025-08-07T10:25:48.881+02:00 level=INFO source=/home/runner/work/dagu/dagu/internal/persistence/filequeue/reader.go:298 msg="Queue full, delaying retry" name=subdomain-enumeration retryAfter=2025-08-07T10:25:50+02:00
```

I removed the data logs and suspend dirs and tested again. No issue - until I scheduled my first DAG.

**Comment by yohamta0** [comment]
@jrisch Can you try removing the files under `data/proc`?

**Comment by jrisch** [comment]
I remove the complete data dir, so `data/proc` is removed too.

**Comment by yohamta0** [comment]
@jrisch I tried your config and DAG, but I wasn't able to reproduce the issue.
However, I’ve applied a some patch and released version 1.19.1. Could you give it a try?

**Comment by yohamta0** [comment]
I think it should be fixed but feel free to let us know if not. Thank you.

**Comment by jrisch** [comment]
Version 1.20.0. Still same issue:

```shell
time=2025-08-12T09:09:39.726+02:00 level=WARN source=/home/runner/work/dagu/dagu/internal/persistence/filequeue/reader.go:313 msg="Timeout waiting for item processing result" name=subdomain-enumeration dagRunId=a1
2025-08-12T09:09:41.3908+02:00 INFO Response: 200 OK service: "http" httpRequest: {url: "http://localhost:8080/api/v2/dag-runs/subdomain-enumeration/a1?remoteNode=local" method: "GET" path: "/api/v2/dag-runs/subdomain-enumeration/a1" remoteIP: "127.0.0.1:64148" proto: "HTTP/1.1" requestID: "MacBookPro.home/peTIETlFjW-000036" scheme: "http" header: {accept: "*/*" accept-language: "en-GB,en-US;q=0.9,en;q=0.8" cookie: "***" connection: "keep-alive" user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36" sec-ch-ua-mobile: "?0" sec-fetch-site: "same-origin" sec-ch-ua: "\"Chromium\";v=\"139\", \"Not;A=Brand\";v=\"99\"" sec-fetch-dest: "empty" referer: "http://localhost:8080/dag-runs/subdomain-enumeration/a1" sec-ch-ua-platform: "\"macOS\"" dnt: "1" sec-fetch-mode: "cors" accept-encoding: "gzip, deflate, br, zstd"}} httpResponse: {status: 200 bytes: 848 elapsed: 0.701916}
time=2025-08-12T09:09:41.777+02:00 level=ERROR source=/home/runner/work/dagu/dagu/internal/scheduler/scheduler.go:423 msg="Cancelling due to timeout waiting for the run to be alive (10sec)" data=subdomain-enumeration:a1
time=2025-08-12T09:09:41.779+02:00 level=DEBUG source=/home/runner/work/dagu/dagu/internal/persistence/filedagrun/attempt.go:172 msg="Initializing status file: /Users/jrisch/Development/process-automation/data/dag-runs/subdomain-enumeration/dag-runs/2025/08/12/dag-run_20250812_070913Z_a1/attempt_20250812_070913_219Z_c5db5f/status.jsonl"
time=2025-08-12T09:09:41.797+02:00 level=INFO source=/home/runner/work/dagu/dagu/internal/scheduler/scheduler.go:319 msg="Received item from queue" data=subdomain-enumeration:a1
time=2025-08-12T09:09:41.798+02:00 level=INFO source=/home/runner/work/dagu/dagu/internal/persistence/filequeue/reader.go:306 msg="Item is invalid, discarding" name=subdomain-enumeration dagRunId=a1
time=2025-08-12T09:09:41.801+02:00 level=INFO source=/home/runner/work/dagu/dagu/internal/scheduler/scheduler.go:374 msg="Skipping item from queue" data=subdomain-enumeration:a1 status=cancelled
```

As soon as I start the first DAG, it takes 10-15 seconds, then the error above pops up in the log file. I've removed all the data directories as usual, before start, so no other DAG is queued up.
